language: ruby
rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  
before_install:
  - gem install bundler  

script: 
  - bundle install
  - bundle exec jekyll build
  
after_script:  
  - gem install type-on-strap
  - gem install jekyll-theme-type-on-strap
  - docker build . -t sylhare-blog
  
notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
